
server:
  address: 0.0.0.0
  port: 9095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tehama_society
    password:
    username: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: madamzainab1999@gmail.com
    password: whusiqzqtuqrkcgc
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
